
# Introduction

To the best of our knowledge the book at hand is the most up-to-date and most complete collection of descriptions of questionnaires to assess ASC experiences. However, several overview articles and collections have been published before. 

Anna Yeginer published in 2000 (in German language) a collection of descriptions of questionnaires for so called "transpersonal psychology", which containes multiple of the questionnaire tools described here. In his book "Bewusstseinszustände: Konzeptualisierung und Messung" (German) Torsten Passie provided an overview of different conceptualizations and of quantitative questionnaire tools, which was a starting point for our collection. We ourselves published a book chapter (also in German language) "Empirische Untersuchung veränderter Bewusstseinszustände (Schmidt & Majic 2017  https://link.springer.com/chapter/10.1007/978-3-642-55125-3_65). At around the same time we started The Altered States Database project which was first published in Schmidt & Berkemeyer (2018). However, there is many more questionnaires available than those to be found on the Altered States Database, which only includes those questionnaires for which a critical amount of studies have been published. Every year we publish a preprint with the current update of the database (See e.g. Prugger et al. 2023, Dewitt et al. 2024).
In 2022 de Deus et al. reported a systematic review to identify questionnaires used in research on psychedelics, which (unsurprisingly) revealed basically the same questionnaires as they can be found on The Altered States Database.
Recently, Yaden et al. (2024) https://www.nature.com/articles/s44159-024-00345-6 discusses multiple questionnaires and their factor structure and validation. Surprisingly, they do not cite The Altered States Database, indicating that the authors were unaware of the existing collection of materials and available data for meta analyses. 

Please also find a slide deck of the workshop [The Empirical Study of Altered States of Consciousness](https://www.researchgate.net/publication/382366098_The_Empirical_Study_of_Altered_States_of_Consciousness_ASSC_Tutorial) (2024) given at the ASSC conference by Dr. Timo Torsten Schmidt, Larry Fort and Cyril Costines. This workshop includes a conceptual overview and additional suggestions and information for empirical research. 

We further compiled a extensive review article on "Classification Schemes of Altered States of Consciousness" (Fort et al. 2024), which also contains the discussion of multiple of the questionnaires that are reviewed in the following.

## Overview 

Multiple questionnaires have been developed to quantify the phenomenology of ASCs. Here, we provide an overview on available psychometric tools, their conceptual background and construction, and validation. Some questionnaires were designed to cover a broad range of different experiences (e.g. the Altered States of Consciousness Rating scale), others are designed to assess specific ASC phenomena (e.g. the Watts Connectedness Scale), and others were designed to assess the phenomena induced by a specific consciousness modifying technique (CMT). Based on their scope and on and prevalence in previous research, we aim to provide aid to decide which questionnaire can be best for a specific study. We discuss the tools in approximate order of prevalence/popularity.
Table 1 gives an overview of the questionnaires in this collection, including some of their basic properties and key references. The most recent (and recommended version) is marked in bold. Wherever available, we included information on new versions under current development (let us know if you know about more).


| Questionnaire  | Version | # items  | # scales | response format 
|-----------|-----------|-----------|-----------|-----------|
| Altered States of Consciousness Rating Scale  | APZ <br /> OAV <br /> 5D-ASC <br /> 11-ASC <br /> 11-ASC(AXP) | 72 <br /> 66 <br /> 94 <br /> 42 <br /> 22 | 3 (FA) <br /> 3(FA) <br /> 5(FA) <br /> 11(FA)<br /> 11  | Yes/No <br /> VAS <br /> VAS <br /> VAS <br /> VAS |
| Phenomenology of Consciousness Inventory | PCI | 53 | 12+14(FA)  | 7-point |
| Addiction Research Center Inventory | ARCI long-form <br /> ARCI short-form | 550 <br /> 49 | 38 <br /> 5 | Yes/No <br /> Yes/No |
| Hallucinogenic Rating Scale | HRS | 126 | 6(FA)  | 5-point |
| Mystical Experience Questionnaire | MEQ <br />  MEQ30 <br /> MEQ-4 <br /> SOCQ <br /> PEQ | 130 <br /> 30 <br />  4 <br /> 100 <br /> 89 | 8+9  <br />  4(FA) <br /> 4 <br />7 <br /> 8 | 6-point <br /> 6-point <br /> 6-point <br /> 6-point <br /> 6,7,8-point|
| Ego-Dissolution Inventory | EDI | 8 | 1 | VAS |
| Emotional Breakthrough Inventory | EBI | 6 | 1 | VAS |
| Challenging Experience Questionnaire | CEQ <br />  CEQ-7 | 26 <br /> 7 <br />  |  7 <br /> 7 <br /> |  6-point <br /> 6-point <br />  |
| Afterglow Inventory | AGI | 24 | 5 | VAS |

__Table 1__ Overview of the most popular questionnaires and their versions that are used to assess ASC phenomena in current research. VAS: Visual Analog Scale; FA: Factor Analysis




[//]: | Questionnaire  | Version | # items  | # scales | response format 
[//]: |-----------|-----------|-----------|-----------|-----------|
[//]: | Watts Connectedness Scale |  |  |  |  |
[//]: | Psychometric States Inventory | PSI | 48 | 6(FA)  | 4-point |
[//]: | Abramson Questionnaire  | AQ |  |  |  |
[//]: | Linton & Lang Questionnaire | LLQ |  |  |  |
[//]: | Near-Death Experience Scale | NDE |  |  |  |
[//]: | The Mysticism Scale | M-Scale |  |  |  |
[//]: | Personal Experience Questionnaire | PEQ |  |  |  |
[//]: | Assessment Schedule for Altered States of Consciousness | ASACS |  |  |  |

[//]: __Table 2__ Overview of additional questionnaires. VAS: Visual Analog Scale; FA: Factor Analysis


