# Phenomenology of Consciousness Inventory (PCI)
The Phenomenology of Consciousness Inventory (PCI) (Pekala, 1982, 1991) was developed in the context of an interdisciplinary approach that is described as empirical-phenomenological (Pekala, 1991). Most notably influenced by C. T. Tart’s (1975) conception of ASCs, it is hypothesized that different states are characterized by distinct structures and patterns of subjective experiences (Pekala, 1991). The subjective experience of a certain state can be characterized based on phenomenologically well-defined dimensions which can be quantified in terms of their intensity. The resulting pattern is assumed to be typical of a specific induction method and can be observed consistently whenever this method is applied.
The PCI is a self-report questionnaire that is completed in retrospect, after acute ASC effects have subsided. Originating from three previous versions, the Phenomenology of Consciousness Questionnaire (PCQ), the (Abbreviated) Dimensions of Consciousness Questionnaire ((A)DCQ), and the Pre-PCI, the most recent version of the PCI is available in two different versions. Form 1 and Form 2 contain the same number of items, which are, however, arranged in a different order. The items of the PCI are presented as two opposing statements located on the two poles of a 7-point Likert scale. The statements address 12 major dimensions, five being further subdivided into more specific sub-dimensions: (1) Altered State of Awareness, (2) Altered Experience (Altered Body Image, Altered Time Sense, Altered Perception, Altered Meaning), (3) Volitional Control, (4) Self-awareness, (5) Rationality, (6) Internal Dialogue, (7) Positive Affect (Joy, Sexual Excitement, Love), (8) Negative Affect (Anger, Sadness, Fear), (9) Imagery (Amount, Vividness), (10) Attention (Direction, Absorption), (11) Memory and (12) Arousal. Corresponding scales were constructed on the basis of several cluster and factor analyses. 

## Validation, Translations, Adaptations
Several studies were conducted in order to evaluate the PCI’s quality in terms of validity and reliability. Assessments of the English PCI under different stimulus conditions (Pekala, 1991) demonstrate good overall internal consistency with an average Cronbach’s alpha ranging from of 0.75 to 0.83 for major  dimensions. Evidence for the PCI’s good validity is given by the comparison with the Dimensions of Attention Questionnaire (DAQ) (0.69< r <0.78) (Pekala, 1991) and the prediction of hypnotic susceptibility as measured with the Harvard Group Scale of Hypnotic Susceptibility (HGSHS) on the basis of the PCI’s major dimensions; e.g. significant correlation (r=0.64, p<0.05) of predicted and actual HGSHS scores using the regression coefficients from a previous study (Pekala, 1995). In the scope of a diploma thesis Rux (2002) evaluated the German version of the PCI. The reliability assessment yielded a medium internal consistency for all scales with alpha coefficients being lowest for Love (0.37) and highest for Altered State of Internal Dialogue (0.86) and an average alpha of 0.69. 
The original version of the PCI was translated from English into German by Ott and subsequently authorized by Pekala (Rux, 2002). An Excel sheet, available from the questionnaire’s author upon request, allows for an automatic computation of item and factor scores.
In summary, this broad questionnaire allows for a quite fine-grained assessment due to its 12 major and 14 minor scales. However, it should be considered that the PCI was designed with a focus on hypnosis and has primarily been applied in studies investigating effects of hypnosis, meditation, and related induction methods like shamanic-journeying or stress management techniques. Its administration in pharmacological studies is rather rare.