# Addiction Research Center Inventory (ARCI)
The ARCI has been developed by Haertzen et al. (1963) in the attempt to measure a broad range of physical, emotive, and cognitive effects of different drugs and subjective experiences related to personality and psychiatric disorders (Haertzen et al., 1963; Haertzen and Hickey, 1987). Items were derived from responses of opiate addicts made in a sentence completion task during baseline, and various drug states and supplemented with items from personality inventories (Haertzen et al., 1963; Haertzen, 1974). A pool of 3300 statements was reduced to a set of 550 true-false items (ARCI long-form) and assigned to five categories: (1) general information, (2) interest and drives, (3) sensation and perception, (4) bodily symptoms and processes, and (5) feelings and attitudes (Haertzen, 1974). Items are mainly phrased in present tense in order to refer to an acute state (Haertzen et al., 1963). Thirty additional items, repeating prior statements in the same or logically opposite form, were included to test for cooperation or carelessness (Haertzen and Hickey, 1987).
To diagnostically differentiate between states, Haertzen and colleagues developed multiple scales to dissociate specific drug intoxications as well as psychiatric conditions (Hill et al., 1963a, 1963b; Haertzen, 1974). A final 38-scales scoring system for the 550-item long form of the ARCI was established (Haertzen, 1974). Amon those various empirical scales were derived with a focus on state-specific effects (Haertzen, 1974).
As the ARCI was not necessarily intended to be applied in its entirety, many studies used only some scales relevant to their specific hypotheses (e.g. (Jasinski et al., 1971)). The most established short form developed by Martin et al. (1971) consists of 49 items that are clustered into five group variability scales: the Benzedrine scale (BG), the Lysergic Acid Diethylamide scale (LSD), the Morphine-Benzedrine and (MBG), and the Pentobarbital-Chlorpromazine-Alcohol scale (PCAG) of the ARCI long form supplemented with the empirically derived 11-item Amphetamine scale (A). Among the plurality of short forms is this the most commonly used questionnaire in current studies (e.g.(Griffiths et al., 2006; Schmid et al., 2015)).

## Validation, Translations, Adaptations
Reliability assessments in five sample populations (criminals, addicts, alcoholics, mentally ill patients, normal population) yielded Kuder-Richardson KR-20 scores for each of the 38 scales (Haertzen, 1970). As the internal consistency demonstrated a large range from 0.06 (Marijuana scale in normal population) to 0.97 (Reactivity in alcoholic sample), the utility of some scales appears rather questionable. In addition, test-retest reliability was assessed (Haertzen, 1970). Several further studies evaluated the psychometric properties of the short form in different languages (Lamas et al., 1994; Arasteh et al., 1999; Riba et al., 2001). Acceptable reliability coefficients are particularly obtained for the Spanish version.
Both long and short form have been translated and validated from English into multiple languages: long form: German, French, Spanish, Swedish (Haertzen, 1974); short form: Spanish (Lamas et al., 1994; Arasteh et al., 1999), French (Warot et al., 1997). Through its availability in different languages, the ARCI was a common instrument to measure drug effects both in clinical settings and experimental research, e.g. including studies on ayahuasca (Riba et al., 2001). As the long form is very time-demanding, the short form (Martin et al., 1971) is more feasible. In particular, its Spanish translation (Lamas et al., 1994) found wide-spread application and has been assessed in terms of psychometric features. However, a recent exploratory factor analysis performed on data from 158 ayahuasca practitioners suggests a three-factor (Euphoria, Activation, Sedation) structure comprising only 18 of the 49 items (Bouso et al., 2016). Another limitation is the application of a dichotomous response format. The use of categorical responses instead of individual intensity ratings precludes any correlational analysis, which is, however, often required in experimental research to establish direct relations between the subjective experience and physiologic measures. 
