
# ToDo's {-}

Here is a list of ToDo's in this book project:

* Workover for Referencses: Check completeness & change to Bibtex Format

* Add a chapter with some basic reflections on Test Theory. In particular it shall include:
  * Information and illustration on the different types of scoring (VAS vs. Likert scales) and anchors that are used
  * Discuss that lately many research groups use digital versions of the questionnaires. For some there still exist paper-pencil versions which have items in a fixed order. In order to address order-effects, for some questionnaires there exist multiple versions. Even though the order-effects are typcially not systematically explored, it appears best practice for online versions to switch to randomizing the order of items.
  * Difference between state and trate questionnaires and their relationship
  * Information about different measures of validity that are typically reported. 
    * Cronbachs Alpha (Consistency)
    * Test-Retest Reliability
  * Terminology: Dimensions, scales, subscales, factors, factor structure
  * Short recap on the most typcial validation procedures:
    * Exploratory Factor Analysis, Confirmatory Factor Analysis, Cluster Analyses
    * Explain shortly what 'Loading' on a factor means and what implications it has if that is not unique
    * Procedures for construction, expert committees, translations (forward backward) etc.
Information on the questionnaires to be added:
* Add systematic information on different validity measures that are reported for each questionnaire.
* Add to overview table details information on different translations to different languages
* Add a section on additional questionnaires, which are relevant in the context of ASC research
    * https://journals.sagepub.com/doi/10.1177/02698811211073758 
    * https://journals.sagepub.com/doi/10.1177/02698811241249698

* Add sections on:
  * Wave; Oña et al. (2020) (Spanish)
  * Dimensions of the Meditative Experience (DME)
  * Meditationstiefefragebogen (MTF)  
* Add some measures from the Cyberdelics literature:
  * Imersiveness
  * Presence 
  
* Add questionnaires for download as PDF with nice typesetting (wherever Copyrights allow it)
* Add Excel analysis sheets to help avoiding mistakes in the analysis


* Add a section about additional quantitative measures which are also interesting for the field of altered states of consciousness research, but not directly concerned with acute experience or after effects (e.g. attitutes to ASC/psychedelics)
  * Add here Zuljevic et al. 2022 (attitudes) https://www.nature.com/articles/s41598-022-23056-5
  * Absorptiveness
  * Hypnotizability
  * Phenomenological Control

