--- 
title: "Consciosuness Assessment Repository"
author: "Timo Torsten Schmidt, Circe e.V."
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Welcome

Welcome to this project of CIRCE e.V. - Collaboration for Research on Conscious Experiences.
We are a collective of researchers who aim to promote research on Altered States of Consciousness (ASC). In this collection of resources, we gather information on questionnaire tools to assess subjective experiences during ASCs. Currently, we have set it up as a bookdwon (gitbook), as this document will undergo continous updates. We call it a "repository" as we plan to supplement the gitbook with different usable versions of the given questionnaires and helpful analysis tools. This might include printable PDFs of the questionnaires and digital versions (e.g. implemenations in different programming languages), as well as analysis tools (e.g. Excel sheets).

If you are intereste to contribute to this collection, you can get in touch with the CIRCE team - in particular with Timo T. Schmidt who is currently the main responsible person for this collection.

This collection is published under CC-BY 4.0

In addition to thecollection at hand, unseful information on the topic has been collected in the following ovrerview articles:

* Fort et al. (2024) Classification Schemes of Altered States of Consciousness (Preprint)
* Yeginer, 2000
* Passie, 2007
* Schmidt & Majic (Book chapter - GERMAN)
* Prugger et al. 2023
* de Deus Pontual A A, Senhorini H G, Corradi- Webster C M, Tófoli L F, Daldegan-Bueno  D (2022): Systematic Review of Psychometric Instruments Used in Research with Psychedelics, Journal of Psychoactive Drugs, DOI: 10.1080/02791072.2022.2079108
* Yaden et al. (2024) https://www.nature.com/articles/s44159-024-00345-6



Acknowledgement: 

The information in this section were collected over multiple years and many people contributed in different ways. Within two study projects in 2017-18 within teaching activities in the MSc program Cognitive Science at the Institute for Cognitive Science at the University of Osnabrück inital information on questionnaires was collected. These study projects were led by Dr. Timo Torsten Schmidt together with Dr. Axel Kohler and Dr. Uwe Friese. After completion of these study projects, several students from different institutions contributed to the collection within internships, labrotations and similar research related activities. 
It was initially planned to publish an overview article and a corresponding manuscript was submitted to a journal. The editor of the journal advised to find a different format for publication and we agree that the accumulated collection of questionnaires (+corresponding background information) will be better accessible in a fully openly access format, which can regularily updated. 
We would like to thank and acknowledge the important contributions of the following people (some of them planned as authors on the intended research article): Katharina Dworatzyk, Ada Drochner, Michal Ljubljanac, Artur Czeszumski, Chiara Carrera, Aliona Cerednicenco, Aalia Nosheen, Philipp Kuhnke, Eelke de Vries, Hendrik Berkemeyer, Renato Garita Figueiredo, Nisha Jagannathan, J Jang, A Kesfhava, J Schott, O Vakhovska, MC Vargas Rivero, Ann Xavier (We hope that we did not forget anyone - otherwise please let us know).
Further we would like to thank the following researchers for providing us with furhter information, discussion and feedback on this collection: Maja Maurer, Rick Strassman, Robin Carhart-Harris, Roland J Pekala, Eric Studerus, Frederick Barrett.


Citation:
If you use the resources that are provided here, it would be nice if you could include the following into your publication:

* 
